const TopMenuItemsLang = {
  p1en: "Hostnames",
  p2en: "Tmetrics",
  p3en: "Srvgrps",
  p4en: "Emails",
  p5en: "Metrics",
  p6en: "Monitors",
  p7en: "MonitorsAll",
  p8en: "MonitorsTable",
  p9en: "Charts",
  p10en: "Privs",
  p101en: "Users",
  p102en: "Resources",
  p103en: "Users-Resources",
  p104en: "Roles",
  p105en: "Users-Roles",
  p106en: "Roles-Resources",
  p11en: "Reports",
  p12en: "ChangeMyPwd",

  p1ru: "Хосты",
  p2ru: "Типы метрик",
  p3ru: "Грп Серверов",
  p4ru: "Emails",
  p5ru: "Метрики",
  p6ru: "Мониторы",
  p7ru: "Все Мониторы",
  p8ru: "МониторыТабл",
  p9ru: "Графики",
  p10ru: "Привилегии",
  p101ru: "Юзеры",
  p102ru: "Ресурсы",
  p103ru: "Юзеры-Ресурсы",
  p104ru: "Роли",
  p105ru: "Юзеры-Роли",
  p106ru: "Роли-Ресурсы",
  p11ru: "Отчеты",
  p12ru: "Смена Пароля",
};

export default TopMenuItemsLang;
